#!/usr/bin/env bash

git log -n 1 --pretty=medium > bench-log

echo -e "\nOLD" >> bench-log
{ 
    time ./bin/reference.exe ./tests/unittests/lib.comparison.art; 
} 2>> bench-log

echo -e "\nCURRENT" >> bench-log
{ 
    time ./bin/arturo.exe ./tests/unittests/lib.comparison.art; 
} 2>> bench-log

git add bench-log
git commit -m "[bench]: update benchmark's log"
