name: Bug Report
description: Describe the problems you have found
title: "[Scope]: Bug Description"
labels: ["bug"]
assignees: ['drkameleon', 'RickBarretto']
body:

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true

  - type: input
    id: Summary
    attributes:
      label: Summary
      description: A clear and concise description of what the bug is.
      placeholder: e.g., "Arturo crashes when using pattern-matching in function `clauses`"
      value: "I have encountered a bug where..."
    validations:
      required: true

  - type: markdown
    id: Current Behavior
    attributes:
      value: |
        ## Current Behavior

    validations:
      required: false

  - type: markdown
    id: Expected Behavior
    attributes:
      value: |
        ## Expected Behavior

    validations:
      required: false

  - type: markdown
    id: Steps To Reproduce
    attributes:
      value: |
        ## Steps To Reproduce

        1. In this environment...
        1. With this config...
        1. Run '...'
        1. See error...
    validations:
      required: false

  - type: input
    attributes:
      label: OS
      description: The operating system you are using (e.g., Windows 11, macOS Ventura, Ubuntu 20.04).
    validations:
      required: true

  - type: input
    attributes:
      label: Version
      description: Arturo's version and build. You can find this by running `arturo --version`.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
