name: Feature request
description: Suggest an improvement for the Arturo language
title: "[Scope]: Feature Description"
labels: [enhancement]
assignees: [drkameleon, RickBarretto]
body:

  - type: input
    id: summary
    attributes:
      label: At a Glance
      description: One-line description of the requested feature.
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Current Issue
      description: Who is impacted and what limitation or friction exists today?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Describe the desired behavior, new syntax, API, or workflow.
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Code examples
      description: Provide code snippets demonstrating the proposed feature in use.
      placeholder: |
        **Before**

        ```art
        $> example code here
        => result
        ```

        **After**

        ```art
        $> example code here
        => result
        ```

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Where does this feature primarily belong?
      multiple: true
      options:
        - Syntax or semantics
        - VM/runtime
        - Standard library
        - REPL / CLI
        - Packages / Package manager
        - Tooling
        - FFI
        - Web
        - Other
    validations:
      required: false

  - type: textarea
    id: compatibility
    attributes:
      label: Impact and compatibility
      description: Note any breaking changes, performance implications, or interactions with existing modules.
      placeholder: |
        - Breaks compatibility with ...
        - Performance is degraded in order of...
    validations:
      required: false

  - type: checkboxes
    id: readiness
    attributes:
      label: Readiness
      description: Help us understand next steps.
      options:
        - label: I can help with implementation
        - label: I can help with tests/spec updates
        - label: I can help with docs/examples

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links, prior art in other languages, related issues, or constraints.
      placeholder: |
        - Related to: #(issue number)
