xyzyabcybdfd => longest unrepeatable substring: [zyabc cybdf] 
xyzyab => longest unrepeatable substring: [zyab] 
zzzzz => longest unrepeatable substring: [z] 
a => longest unrepeatable substring: [a] 
 => longest unrepeatable substring: []