/*****************************************************************
 * Arturo :VM
 * 
 * Programming Language + Compiler
 * (c) 2019-2020 Yanis Zafirópulos (aka Dr.Kameleon)
 *
 * @file: src/main.c
 *****************************************************************/

#include "arturo.h"
#include "version/version.h"

/**************************************
  Helpers
 **************************************/

void showVersion() {
	struct utsname unameData;
	uname(&unameData);

    printf("\x1B[32m\x1B[1mArturo %s\x1B[0m (%s build %s) [%s-%s]\n",Version,BuildDate,BuildNo,unameData.machine,unameData.sysname);
    printf("(c) 2019-2020 Yanis Zafirópulos\n");
    printf("\n");
}

void showHelp(){
	showVersion();

	printf("\e[1;37musage:\e[00m arturo [options] <filename> [args...]\n\n");

	printf("\e[1;36mcommand\e[00m\n");
	printf("    -h           - show (this) help information\n");
	printf("    -v           - show version\n\n");
	
	printf("\e[1;36moptions\e[00m\n");
    printf("    -i PATH      - set include path\n");
    printf("    -s SIZE      - set VM stack size\n");
    printf("\n");
    printf("    -b           - print generated bytecode\n");
    printf("    -c           - compile only\n");
    printf("    -o           - optimize code\n");
    printf("    -x           - execute object file\n");
	printf("\n");
}

/**************************************
  The Main Entry
 **************************************/

int main(int argc, char** argv) {

    // process command-line arguments
    /*
    {
        static void* caseArg0[] = {
            &&I0, &&R0
        };

        goto *caseArg0[1];

        I0: printf("in I0\n"); goto endd;
        R0: printf("in R0\n"); goto endd;
        endd: printf("after IF\n");
    }
    {
        __label__ caseArg0[] = {
            &I0, &R0
        };

        goto *caseArg0[1];

        I0: printf("in I0\n"); goto endd;
        R0: printf("in R0\n"); goto endd;
        endd: printf("after IF\n");
    }*/
    
	char* includePath = NULL;
    unsigned int stackSize = 0;
    bool compileOnly = false;
    bool executeObject = false;
    bool doOptimize = false;
    bool doDebugBytecode = false;

	int opt; 

	while((opt = getopt(argc, argv, "hvi:s:cxbo")) != -1) {  
        switch(opt) {  
        	case 'h':
        		showHelp();
        		exit(0);
        	case 'v':
        		showVersion();
        		exit(0);
        	case 'i':
        		includePath = optarg;
        		break;
            case 's': {
                char* endp = NULL;
                long l = -1;
                if (!optarg ||  ((l=strtol(optarg, &endp, 10)),(endp && *endp))) {
                    printf("expecting valid SIZE argument for option -s\n");
                    exit(1);
                }
                stackSize = (int)l;
                break;
            }
            case 'c':
                compileOnly = true;
                break;
            case 'x':
                executeObject = true;
                break;
            case 'b':
                doDebugBytecode = true;
                break;
            case 'o':
                doOptimize = true;
                break;
        	default:
        		exit(1);
        }  
    }  

    int extraArgs = argc-optind;
    Env = (Environment){
        .littleEndian = IS_LITTLE_ENDIAN,
        .include = includePath,
        .stackSize = (stackSize==0 ? STACK_SIZE : stackSize),
        .optimize = doOptimize,
        .debugBytecode = doDebugBytecode,
        .argv = argv,
        .argi = optind
    };

    if (compileOnly && executeObject) {
        cmdlineError("cannot use -c and -x simultaneously");
    }

    if (!extraArgs) {
        if (compileOnly || executeObject) {
            cmdlineError("cannot use -c or -x without an input file");
        }
        if (doOptimize) {
            cmdlineError("extraneous argument -O found");
        }
    	replStart();
    }
    else {
        if (compileOnly) {
            vmCompileScript(argv[optind]);
        }
        else if (executeObject) {
            vmRunObject(argv[optind]);
        }
        else {
            vmRunScript(argv[optind]);
        }
    }

    return 0;
}

/****************************************
   This is the end,
   my only friend, the end...
 ****************************************/