name: "MacOS"
on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'
  pull_request:
    paths-ignore:
      - 'docs/*'
      - '*.yml'
      - '*.md'
      - 'LICENSE'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  
  build:
    name: "Build & Test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-12
          - macos-14
        version:
          - mini
          - full
        arch:
          - amd64
          - arm64
        exclude:
          - os: macos-12
            arch: arm64
          - os: macos-14
            arch: amd64

    steps:
      - name: "Checkout"
        uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Get Date
        id: get-date
        run: echo "::set-output name=date::$(date "+%Y-%m-%d")"
        shell: bash

      - name: Cache ChooseNim
        id: cache-choosenim
        uses: actions/cache@v3
        with:
          path: ~/.choosenim
          key: ${{ matrix.os }}-choosenim-${{ steps.get-date.outputs.date }}

      - name: Cache Nimble
        id: cache-nimble
        uses: actions/cache@v3
        with:
          path: ~/.nimble
          key: ${{ matrix.os }}-nimble-${{ hashFiles('*.nimble') }}

      - name: Setup nim
        if: matrix.arch == 'arm64'
        run: |
          brew install nim
          brew install gmp
          brew install pcre
          brew install mpfr
 
      - name: Setup nim (amd64)
        if: matrix.arch == 'amd64'
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '2.0.4'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify dependecies
        run: |
          nim --version
          
      - name: Build Arturo
        run: |
          echo "./bin" >> $GITHUB_PATH
          ./build.nims build --mode ${{ matrix.version }} --arch ${{ matrix.arch }} --log
           
      - name: Upload Artifacts
        uses: 'actions/upload-artifact@v2'
        with:
          name: "arturo-${{matrix.version}}-${{matrix.arch}}-macos"
          path: bin/arturo

      - name: Run unit tests (full)
        if: matrix.version == 'full'
        run: |
          arturo tools/tester.art
          ./bin/arturo tools/unitt-tester.art

      - name: Run unit tests (mini)
        if: matrix.version == 'mini'
        run: |
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
          arturo tools/tester.art